# Generated by Django 5.0.3 on 2024-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_phone_number_alter_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
